services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/*'
        exclude:
        - '../src/Entity/'
        - '../src/Kernel.php'
        - '../src/Database/DatabaseConnectionInterface.php'
    Psr\Log\LoggerInterface:
        class: \Monolog\Logger
        arguments:
            $name: 'logger'
    App\Database\DatabaseConnectionInterface:
        class:
            App\Database\DatabaseConnection
    App\Repositories\CommentRepository:
        class:
            App\Repositories\CommentRepository
        arguments:
            $databaseConnection: '@App\Database\DatabaseConnectionInterface'
            $commentBuilder: '@App\Repositories\Builder\CommentBuilder'
            $logger: '@Psr\Log\LoggerInterface'
    App\Repositories\NewsRepository:
        class:
            App\Repositories\NewsRepository
        arguments:
            $databaseConnection: '@App\Database\DatabaseConnectionInterface'
            $commentManager: '@App\Repositories\CommentRepository'
            $newsBuilder: '@App\Repositories\Builder\NewsBuilder'
            $logger: '@Psr\Log\LoggerInterface'

